"""Initial migration

Revision ID: d4d879f8db88
Revises: 
Create Date: 2025-04-27 23:16:33.883639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4d879f8db88'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor_patient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.String(length=10), nullable=False),
    sa.Column('patient_id', sa.String(length=10), nullable=False),
    sa.Column('assigned_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('doctor_patient')
    # ### end Alembic commands ###
